#pragma once

#include <algorithm>
#include <array>
#include <coroutine>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <memory>
#include <numeric>
#include <optional>
#include <ranges>
#include <regex>
#include <set>
#include <source_location>
#include <sstream>
#include <stacktrace>
#include <stdexcept>
#include <string>
#include <vector>
#include <iostream>
#include <fstream>
#include <ctime>
#include <sstream>
#include <memory>
#include <vector>